# Generated by Django 3.0.3 on 2020-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200407_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/profile.jpg', upload_to='profile_pics'),
        ),
    ]
