# Generated by Django 3.0.3 on 2020-04-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('checkout', '0002_remove_orderlineitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
