# Generated by Django 3.0.3 on 2020-04-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('checkout', '0003_orderlineitem_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
